services:
  flask-app:
    build:
      context: .
    ports:
      - "5015:5015"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    env_file:
      - .env
    restart: always