services:
  flask-app:
    build:
      context: .
    ports:
      - "5010:5010"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    env_file:
      - .env