services:
  flask-app:
    build:
      context: .
    ports:
      - "5010:5010"
    volumes:
      - .:/app
    environment:
      NODE_ENV: production
      PYTHONUNBUFFERED: 1  # 🔥 Fuerza a Python a imprimir en tiempo real
    env_file:
      - .env